"""add patient monitoring paused and archive status fields

Revision ID: 0aa8b94fc831
Revises: 8efb7391cb8e
Create Date: 2026-06-02 17:01:12.100996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa8b94fc831'
down_revision: Union[str, None] = '8efb7391cb8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Step 1: Add columns allowing NULL values temporarily
    op.add_column('patients', sa.Column('is_monitoring_paused', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('is_discharged', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('archive_status', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('discharged_at', sa.DateTime(), nullable=True))

    # 2. Step 2: Populate defaults for your existing rows so they are not empty
    op.execute("UPDATE patients SET is_monitoring_paused = FALSE WHERE is_monitoring_paused IS NULL")
    op.execute("UPDATE patients SET is_discharged = FALSE WHERE is_discharged IS NULL")
    op.execute("UPDATE patients SET archive_status = 'active' WHERE archive_status IS NULL")

    # 3. Step 3: Now apply the strict NOT NULL constraints safely
    op.alter_column('patients', 'is_monitoring_paused', nullable=False)
    op.alter_column('patients', 'is_discharged', nullable=False)
    op.alter_column('patients', 'archive_status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('patients', 'device_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('patients', 'archive_status')
    op.drop_column('patients', 'discharged_at')
    op.drop_column('patients', 'is_discharged')
    op.drop_column('patients', 'is_monitoring_paused')
    # ### end Alembic commands ###
