"""Column ward_id added in Alert table

Revision ID: 42ce60419da9
Revises: c7fdcca3f9aa
Create Date: 2026-04-01 07:10:46.656228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ce60419da9'
down_revision: Union[str, None] = 'c7fdcca3f9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('ward_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alerts_ward_id'), 'alerts', ['ward_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_ward_id'), table_name='alerts')
    op.drop_column('alerts', 'ward_id')
    # ### end Alembic commands ###
