"""add_org_hierarchy_tables

Revision ID: 4ef7c3b57605
Revises: 68fd65125e60
Create Date: 2026-03-31 15:04:07.305738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef7c3b57605'
down_revision: Union[str, None] = '68fd65125e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
