"""Added nurse_id to patients

Revision ID: 53265ace6eee
Revises: 42ce60419da9
Create Date: 2026-04-06 14:30:11.467601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53265ace6eee'
down_revision: Union[str, None] = '42ce60419da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('nurse_id', sa.Integer(), nullable=True))
    op.alter_column('patients', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'patients', 'nurses', ['nurse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.alter_column('patients', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('patients', 'nurse_id')
    # ### end Alembic commands ###
