"""add_org_hierarchy_tables

Revision ID: 68fd65125e60
Revises: b9cc350f1ca9
Create Date: 2026-03-31 14:33:41.026425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68fd65125e60'
down_revision: Union[str, None] = 'b9cc350f1ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wards_id'), 'wards', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.add_column('organizations', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('organizations', sa.Column('state', sa.String(length=100), nullable=False))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=False))
    op.drop_index('ix_organizations_org_code', table_name='organizations')
    op.drop_constraint('organizations_name_key', 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_city'), 'organizations', ['city'], unique=False)
    op.create_index(op.f('ix_organizations_country'), 'organizations', ['country'], unique=False)
    op.create_index(op.f('ix_organizations_state'), 'organizations', ['state'], unique=False)
    op.drop_column('organizations', 'org_code')
    op.drop_column('organizations', 'created_at')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'is_active')
    op.add_column('patients', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('patients', sa.Column('gender', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('patients', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('patients', sa.Column('alt_phone', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('device_id', sa.String(length=100), nullable=False))
    op.add_column('patients', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.add_column('patients', sa.Column('room_id', sa.Integer(), nullable=False))
    op.alter_column('patients', 'blood_group',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               nullable=False)
    op.create_index(op.f('ix_patients_device_id'), 'patients', ['device_id'], unique=True)
    op.create_foreign_key(None, 'patients', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(None, 'patients', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_device_id'), table_name='patients')
    op.alter_column('patients', 'blood_group',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               nullable=True)
    op.drop_column('patients', 'room_id')
    op.drop_column('patients', 'doctor_id')
    op.drop_column('patients', 'device_id')
    op.drop_column('patients', 'alt_phone')
    op.drop_column('patients', 'weight')
    op.drop_column('patients', 'height')
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'age')
    op.add_column('organizations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('org_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_organizations_state'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_country'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_city'), table_name='organizations')
    op.create_unique_constraint('organizations_name_key', 'organizations', ['name'])
    op.create_index('ix_organizations_org_code', 'organizations', ['org_code'], unique=True)
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'country')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_wards_id'), table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
