"""Add is_on_call firld in doctor table

Revision ID: 87d3d616460d
Revises: 53265ace6eee
Create Date: 2026-04-07 12:12:05.048150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d3d616460d'
down_revision: Union[str, None] = '53265ace6eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('is_on_call', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'is_on_call')
    # ### end Alembic commands ###
