"""Add snooze and resolve to alerts

Revision ID: 8efb7391cb8e
Revises: 9c57e47eda8a
Create Date: 2026-05-17 04:46:52.425139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efb7391cb8e'
down_revision: Union[str, None] = '9c57e47eda8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('snoozed_until', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('is_resolved', sa.Boolean(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alerts', 'users', ['resolved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'resolved_by')
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'is_resolved')
    op.drop_column('alerts', 'snoozed_until')
    # ### end Alembic commands ###
