"""add patient calibration table

Revision ID: 9c57e47eda8a
Revises: 87d3d616460d
Create Date: 2026-05-12 15:21:12.917326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c57e47eda8a'
down_revision: Union[str, None] = '87d3d616460d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('actual_temp', sa.Float(), nullable=True),
    sa.Column('sensor_temp', sa.Float(), nullable=True),
    sa.Column('temp_offset', sa.Float(), nullable=True),
    sa.Column('actual_systolic', sa.Integer(), nullable=True),
    sa.Column('sensor_systolic', sa.Integer(), nullable=True),
    sa.Column('systolic_offset', sa.Integer(), nullable=True),
    sa.Column('actual_diastolic', sa.Integer(), nullable=True),
    sa.Column('sensor_diastolic', sa.Integer(), nullable=True),
    sa.Column('diastolic_offset', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_calibrations')
    # ### end Alembic commands ###
