"""add_organizations_table

Revision ID: b9cc350f1ca9
Revises: cb86ebc9b46c
Create Date: 2026-03-30 19:03:28.687017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9cc350f1ca9'
down_revision: Union[str, None] = 'cb86ebc9b46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('org_code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_org_code'), 'organizations', ['org_code'], unique=True)
    op.drop_constraint('doctors_license_number_key', 'doctors', type_='unique')
    op.drop_column('doctors', 'license_number')
    op.add_column('nurses', sa.Column('license_no', sa.String(length=50), nullable=False))
    op.drop_constraint('nurses_license_number_key', 'nurses', type_='unique')
    op.create_unique_constraint(None, 'nurses', ['license_no'])
    op.drop_column('nurses', 'license_number')
    op.drop_column('nurses', 'department')
    op.drop_column('patients', 'date_of_birth')
    op.add_column('users', sa.Column('user_id', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'user_id')
    op.add_column('patients', sa.Column('date_of_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('nurses', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('nurses', sa.Column('license_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nurses', type_='unique')
    op.create_unique_constraint('nurses_license_number_key', 'nurses', ['license_number'])
    op.drop_column('nurses', 'license_no')
    op.add_column('doctors', sa.Column('license_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('doctors_license_number_key', 'doctors', ['license_number'])
    op.drop_index(op.f('ix_organizations_org_code'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
