"""make device_id and room_id nullable for discharge tracking

Revision ID: d8958e96c0c1
Revises: 0aa8b94fc831
Create Date: 2026-06-02 17:19:28.412991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8958e96c0c1'
down_revision: Union[str, None] = '0aa8b94fc831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Safely alter columns to allow NULL structures upon patient checkouts
    op.alter_column('patients', 'device_id', existing_type=sa.String(length=100), nullable=True)
    op.alter_column('patients', 'room_id', existing_type=sa.Integer(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('patients', 'device_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
